#! /bin/bash

if [ $# != 3 ]; then
  echo "$0: Give: 
		   1:file path 
		   2:number of slices 
		   3:extension"
			
else
  echo "file path:" $1
  echo "slices:" $2
  echo "extension:" $3

fileName=$1
dir=`dirname "${fileName}"`
numbSamps=`soxi -s "${fileName}"`
Slice=$(( $numbSamps / $2 ))
eind=$Slice
begin=0


for(( i=1; i<=$2; i++ ))
do
	newFile="${dir}"/`basename "${fileName}" .wav`$i.wav
	sox "${fileName}" "${newFile}" trim $begin"s" =$eind"s"
	begin=$(( $begin + $Slice ))
	eind=$(( $eind + $Slice ))

done


fi


