#! /bin/bash

path="`pwd`/converted_files" 
fileType=.$1
encodType=.$2

if ([ $# != 2 ]); then
	echo "$0: give:
		  1:file type:
		  2:encoder type:"
		exit
				
else
	
	echo "$0: path:" $path
	echo "$0: filetype:" $fileType
	echo "$0: encodertype:" $encodType
	echo -n "$0: ""are you sure? (yes/no) "
	read var_answer	
	
	if [ $var_answer == "yes" ]; then
		
		
		for file in *$fileType ; do 
		echo "$0: converting: "${file}" to "${path}""
		outFile="`basename "${file}" $fileType`$encodType"
		lame -V2 "${file}" /"${path}"/"${outFile}" ;
		open /"${path}"
	 done
		
	elif [ $var_answer == "no" ]; then
		
		echo "$0: quit"
		exit
		
	else echo "$0: invalid input"
		 exit
	fi	
fi
