#! /bin/bash

path="`pwd`/converted_files"
fileType=.$1
encodType=.$2

if ([ $# != 2 ]); then
	echo "$0: give:
		  1:file type:
		  2:encoder type:"
		exit

else

if ([ $fileType == ".wav" ] ||[ $fileType ==  ".aiff" ]) &&
	   ([ $encodType == ".mp3" ] || [ $encodType == ".flac" ] ||
		  [ $encodType == ".ogg" ]); then

	echo "$0: path:" $path
	echo "$0: filetype:" $fileType
	echo "$0: encodertype:" $encodType
	echo -n "$0: ""are you sure? (y/n) "
	read var_answer

	if [ $var_answer == "y" ]; then

		if [ ! -d "${path}" ]; then
			mkdir "${path}"
		fi

		for file in *$fileType ; do
		echo "$0: converting: "${file}" to "${path}""
		outFile="`basename "${file}" $fileType`$encodType"
		lame -V2 "${file}" /"${path}"/"${outFile}" ;

	 done
		 open /"${path}"

	elif [ $var_answer == "n" ]; then

		echo "$0: quit"
		exit

	else echo "$0: invalid input"
		 exit
		fi

	else echo "$0: Wrong type, please choose:
		-input format: wav, aiff
		-output format: mp3, flac, ogg"
	fi
fi
