all: somfunc print_array max_array rot_array

somfunc: somfunc.cpp
	g++ -c somfunc.cpp
	g++ -o somfunc somfunc.o


print_array: print_array.cpp
	g++ -c print_array.cpp
	g++ -o print_array print_array.o

max_array: max_array.cpp
		g++ -c max_array.cpp
		g++ -o max_array max_array.o


rot_array: rot_array.cpp
		g++ -c rot_array.cpp
		g++ -o rot_array rot_array.o

