CC = g++
CFLAGS = -g -Wall


all: twothreads thread_int thread_struct \
     identicalthreads thread_join thread_detaching \
     nomutex mutex \
     deadlock thread_scheduling msgqueue

twothreads: twothreads.o
	$(CC) -o $@ $(CFLAGS) twothreads.o -lpthread

thread_int: thread_int.o
	$(CC) -o $@ $(CFLAGS) thread_int.o -lpthread

thread_struct: thread_struct.o
	$(CC) -o $@ $(CFLAGS) thread_struct.o -lpthread

identicalthreads: identicalthreads.o
	$(CC) -o $@ $(CFLAGS) identicalthreads.o -lpthread

thread_join: thread_join.o
	$(CC) -o $@ $(CFLAGS) thread_join.o -lpthread

thread_detaching: thread_detaching.o
	$(CC) -o $@ $(CFLAGS) thread_detaching.o -lpthread

mutex: mutex.o
	$(CC) -o $@ $(CFLAGS) mutex.o -lpthread

nomutex: nomutex.o
	$(CC) -o $@ $(CFLAGS) nomutex.o -lpthread

deadlock: deadlock.o
	$(CC) -o $@ $(CFLAGS) deadlock.o -lpthread

thread_scheduling: thread_scheduling.o
	$(CC) -o $@ $(CFLAGS) thread_scheduling.o -lpthread

msgqueue: msgqueue.o
	$(CC) -o $@ $(CFLAGS) msgqueue.o -lpthread



.cpp.o:
	$(CC) -c $< $(CFLAGS)

clean:
	rm -f *.o twothreads thread_int thread_struct \
		identicalthreads thread_join thread_detaching \
		mutex nomutex deadlock thread_scheduling msgqueue
